apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  mysql_root_password: {{ .Values.deployment.mysql.root | toString | b64enc | quote }}
type: Opaque