apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.nfsClientProvisioner.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nfs-client-provisioner.labels" . | nindent 4 }}