deployment:
  vllm:
    image: kelcin-vllm-cpu-env
    imageTag: v0.7.3
    modelDir: Meta-Llama-3-8B-Instruct
    servedModelName: llama3
    args:
      - "--max-model-len"
      - "8192"
    vllmCpuKvcacheSpace: 4
    resources:
      limits:
        cpu: 10
        memory: 22Gi
      requests:
        cpu: 10
        memory: 22Gi
    customChatTemplate: llama3