apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.deployment.rayServe.configVolumeName | quote }}
  labels:
    {{- include "ray-serve.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.deployment.rayServe.storage }}
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: {{ printf "%s-%s" .Release.Namespace .Values.deployment.rayServe.configVolumeName | quote }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-%s" .Release.Namespace .Values.deployment.rayServe.configVolumeName | quote }}
  labels:
    {{- include "ray-serve.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.deployment.rayServe.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: {{ .Values.deployment.rayServe.configVolumeName | quote }}
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: {{ .Values.deployment.rayServe.configVolumePath | quote }}
    type: DirectoryOrCreate