{{- $maxOngoingRequests := .Values.deployment.rayServe.modelConfig.maxOngoingRequests -}}
{{- $logLevel := .Values.deployment.rayServe.modelConfig.logLevel -}}
{{- $type := .Values.deployment.rayServe.modelConfig.type -}}
{{- $beamSize := .Values.deployment.rayServe.modelConfig.beamSize -}}
{{- $quantization := .Values.deployment.rayServe.modelConfig.quantization -}}
{{- $patience := .Values.deployment.rayServe.modelConfig.patience -}}
{{- $maxPositionEmbeddings := .Values.deployment.rayServe.modelConfig.maxPositionEmbeddings -}}
{{- range $groupName, $group := .Values.deployment.rayServe.modelConfig.models }}
{{- $g := include "ray-serve.standardizeGroupName" (dict "group" $groupName) -}}
{{- $models := include "ray-serve.CalModelConfig" (dict "Values" $.Values "group" $groupName) | fromJsonArray -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ray-serve-config-cm{{ $g }}
  labels:
    {{- include "ray-serve.labels" $ | nindent 4 }}
data:
  serve_config: |-
    proxy_location: EveryNode

    http_options:
      host: 0.0.0.0
      port: 8000

    logging_config:
      encoding: TEXT
      log_level: INFO
      logs_dir: null
      enable_access_log: true

    applications:
    - name: Health
      route_prefix: /health
      import_path: ray-serve:app_builder
      deployments:
      - name: Health
      args:
        type: Health
        health_name: Health
        app_num: {{ $models | len | quote }}
    {{- range $models }}
    {{- $modelType := "type" | hasKey . | ternary .type $type }}
    - name: {{ .name }}
      route_prefix: /{{ .name }}
      import_path: ray-serve:app_builder
      deployments:
      - name: {{ $modelType }}
        max_ongoing_requests: {{ "maxOngoingRequests" | hasKey . | ternary .maxOngoingRequests $maxOngoingRequests }}
        logging_config:
          log_level: {{ "logLevel" | hasKey . | ternary .logLevel $logLevel }}
        ray_actor_options:
        {{- if "numGpus" | hasKey . }}
          num_gpus: {{ .numGpus }}
        {{- end }}
        {{- if "numCpus" | hasKey . }}
          num_cpus: {{ .numCpus }}
        {{- end }}
      args:
        type: {{ $modelType }}
        model_path: /models/{{ .name }}
        {{- if "Translator" | eq $modelType }}
        max_position_embeddings: {{ "maxPositionEmbeddings" | hasKey . | ternary .maxPositionEmbeddings $maxPositionEmbeddings | quote }}
        qnt: {{ "quantization" | hasKey . | ternary .quantization $quantization | quote }}
        beam_size: {{ "beamSize" | hasKey . | ternary .beamSize $beamSize | quote }}
        patience: {{ "patience" | hasKey . | ternary .patience $patience | quote }}
        {{- end }}
    {{- end }}
---
{{- end }}