apiVersion: v1
kind: Service
metadata:
  name: ray-serve-svc
  labels:
    {{- include "ray-serve.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: ray-serve-port
    protocol: TCP
    name: service
  - port: {{ .Values.service.dashboardPort }}
    targetPort: dashboard-port
    protocol: TCP
    name: dashboard
  selector:
    {{- include "ray-serve.selectorLabels" . | nindent 4 }}
    app: ray-serve
