apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    {{- include "nfs-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nfs-server.selectorLabels" . | nindent 6 }}
      app: nfs-server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nfs-server.labels" . | nindent 8 }}
        app: nfs-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nfs-server
          image: {{ .Values.deployment.nfsServer.image }}:{{ .Values.deployment.nfsServer.imageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
              - SYS_ADMIN
              - SYS_MODULE
          env:
          - name: NFS_SERVER_THREAD_COUNT
            value: {{ .Values.deployment.nfsServer.resources.limits.cpu | int | mul 4 | quote }}
          {{- if .Values.deployment.nfsServer.onlyNFSv4 }}
          - name: NFS_DISABLE_VERSION_3
            value: "1"
          {{- end }}
          {{- if .Values.deployment.nfsServer.debugInfo }}
          - name: NFS_LOG_LEVEL
            value: "DEBUG"
          {{- end }}
          ports:
            - containerPort: 2049
              protocol: TCP
              name: tcp-2049
            - containerPort: 2049
              protocol: UDP
              name: udp-2049
            {{- if .Values.deployment.nfsServer.onlyNFSv4 | not }}
            - containerPort: 111
              protocol: TCP
              name: tcp-111
            - containerPort: 111
              protocol: UDP
              name: udp-111
            - containerPort: 32765
              protocol: TCP
              name: tcp-32765
            - containerPort: 32765
              protocol: UDP
              name: udp-32765
            - containerPort: 32767
              protocol: TCP
              name: tcp-32767
            - containerPort: 32767
              protocol: UDP
              name: udp-32767
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: 2049
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 2049
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.deployment.nfsServer.resources | nindent 12 }}
          volumeMounts:
            - name: load-module
              mountPath: /lib/modules
              readOnly: true
            - name: exports
              mountPath: /etc/exports
              subPath: exports
              readOnly: true
            - name: nfs
              mountPath: {{ .Values.deployment.nfsServer.hostPath }}
      volumes:
        - name: load-module
          persistentVolumeClaim:
            claimName: pvc-nfs-server-load-kernel-modules
        - name: exports
          configMap:
            name: nfs-server-exports-cm
            items:
              - key: exports.txt
                path: exports
        - name: nfs
          persistentVolumeClaim:
            claimName: pvc-nfs-server
      nodeSelector:
        {{- toYaml .Values.deployment.nfsServer.nodeSelector | nindent 8 }}