apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-server-load-kernel-modules
spec:
  resources:
    requests:
      storage: 150Mi
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-nfs-server-load-kernel-modules
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-server-load-kernel-modules
spec:
  capacity:
    storage: 150Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: pvc-nfs-server-load-kernel-modules
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: /lib/modules
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-server
spec:
  resources:
    requests:
      storage: {{ .Values.deployment.nfsServer.storage }}
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-nfs-server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-server
spec:
  capacity:
    storage: {{ .Values.deployment.nfsServer.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: pvc-nfs-server
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: {{ .Values.deployment.nfsServer.hostPath }}
    type: DirectoryOrCreate