apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-server-load-kernel-modules
spec:
  resources:
    requests:
      storage: 150Mi
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-nfs-server-load-kernel-modules
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-server-load-kernel-modules
spec:
  capacity:
    storage: 150Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: pvc-nfs-server-load-kernel-modules
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: /lib/modules
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-server-rw
spec:
  resources:
    requests:
      storage: {{ .Values.deployment.nfsServer.rwStorage }}
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-nfs-server-rw
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-server-rw
spec:
  capacity:
    storage: {{ .Values.deployment.nfsServer.rwStorage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: pvc-nfs-server-rw
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: {{ .Values.deployment.nfsServer.hostPath.write }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-server-ro
spec:
  resources:
    requests:
      storage: {{ .Values.deployment.nfsServer.roStorage }}
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-nfs-server-ro
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-server-ro
spec:
  capacity:
    storage: {{ .Values.deployment.nfsServer.roStorage }}
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: pvc-nfs-server-ro
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: {{ .Values.deployment.nfsServer.hostPath.read }}
    type: DirectoryOrCreate