apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openclaw-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-openclaw.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openclaw-role
subjects:
  - kind: ServiceAccount
    name: openclaw-sa
    namespace: {{ .Release.Namespace }}
