{{- $apiKey:= .Values.deployment.openclaw.model.config.apiKey -}}
{{- if empty $apiKey -}}
{{- fail "deployment.openclaw.model.config.apiKey is required" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-openclaw.labels" . | nindent 4 }}
data:
  _authToken: {{ include "my-openclaw.getAuthToken" . | toString | b64enc | quote }}
  _apiKey: {{ $apiKey | toString | b64enc | quote }}
type: Opaque