apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secret
  labels:
    {{- include "my-openclaw.labels" . | nindent 4 }}
data:
  _authToken: {{ include "my-openclaw.getAuthToken" . | toString | b64enc | quote }}
type: Opaque