# Default values for ray-serve.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  dashboardPort: 8265

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

deployment:
  rayServe:
    image: kelcin-ray-serve
    imageTag: 3.0.0
    tz: "Asia/Shanghai"
    configVolumeName: config-volume
    dataVolumeName: data-volume
    loggingVolumeName: logging-volume
    resources:
      limits:
        cpu: 5
        memory: 12Gi
      requests:
        cpu: 4
        memory: 10Gi
    modelConfig:
      maxOngoingRequests: 100
      logLevel: DEBUG
      type: Translator
      # float16 or float32
      quantization: float16
      beamSize: 3
      patience: 1
      numCpus: 3
      models:
        rayServe:
          models:
          - name: opus-mt-en-zh
            enabled: false
          - name: opus-mt-zh-en
            enabled: false
          - name: m2m100_418M
            enabled: false
          - name: multilingual-e5-large-instruct
            type: Embedding
            enabled: true
          - name: bge-reranker-v2-m3
            type: Reranker
            enabled: true
